# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('logradouro', models.CharField(max_length=30, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=3, verbose_name='Numero')),
                ('admin', models.BooleanField(verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='Numero')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciaralimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAlimento', models.CharField(max_length=50, verbose_name='CodAlimento ')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('porcao', models.CharField(max_length=50, verbose_name='Porcao ')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preco ')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('forma_pagamento', models.CharField(max_length=14, verbose_name='Forma de Pagamento')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=3, verbose_name='Quantidade')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.CharField(max_length=4, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='id_tipoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_produto'),
        ),
        migrations.AddField(
            model_name='pedido_produto',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
