# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171213_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='data'),
        ),
    ]
