# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171213_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='grama',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
