# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171218_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=20, verbose_name='Email'),
        ),
    ]
